apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-podman
  namespace: kube-podman
  labels:
    project: kube-podman
    owner: mrgoonie
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kube-podman
  template:
    metadata:
      labels:
        owner: mrgoonie
        app: kube-podman
        project: kube-podman
    spec:
      containers:
        - name: kube-podman
          image: mrgoonie/kube-podman:9
          securityContext:
            # run as "root" user
            # runAsUser: 0
            # run as "app" user
            runAsUser: 1000
            runAsGroup: 1000
            # seLinuxOptions:
            #   type: spc_t
            capabilities:
              add:
                - "SYS_ADMIN"
                - "MKNOD"
                - "SYS_CHROOT"
                - "SETFCAP"
            # capabilities:
            #   add:
            #     - "SYS_ADMIN"
            #     - "MKNOD"
            #     - "SYS_CHROOT"
            #     - "SETFCAP"
            #     - "SYS_RESOURCE"
            #     - "SETUID"
            #     - "SETGID"
          resources:
            limits:
              github.com/fuse: 1
          # env:
          #   - name: TZ
          #     value: Asia/Ho_Chi_Minh
          # volumeMounts:
          #   - mountPath: /home/app/.local/share/containers
          #     name: podman-local
      # volumes:
      #   - name: podman-local
      #     hostPath:
      #       path: /home/dev/kube-podman/.local/share/containers
